steemnova/steemnova

- includes/classes/class.FleetFunctions.php
Fixes this
https://steemit.com/utopian-io/@barbarossastudio/fleet-transfer-time-bug
> Fix Recall Mission Hold time before it reaches Planet

- scripts/backend/README.md
- scripts/backend/dark_matter.py
> Adding black_matter.py for automated DM distribution based on incoming transactions

- includes/classes/missions/MissionCaseExpedition.class.php
Chances changed to:
- Find resources: 32,5%. Values from http://owiki.de/Expedition
- Find Dark Matter: 9%. Values from 2Moons
- Find abandoned ships: 22%. Values from http://owiki.de/Expedition , took 80% data.
- Find pirates or aliens: 8,4%. 50/50 pirates or aliens.
- Black hole: 0,3%
- The fleet delays or return earlier: 9%
- Find nothing: 18,8%...
Resolve https://github.com/steemnova/steemnova/issues/16
Proposition http://wiki.ogame.org/index.php/Guide:Expedition_guide
> Adjust randomness of Expedition mission

- language/pl/ADMIN.php
- language/pl/FLEET.php
- language/pl/INGAME.php
- language/pl/LANG.cfg
- language/pl/TECH.php
Edited little typos and few german leftovers.
Still need to read all of it but it will be better to update while needed (i.e. while reported by users).
> few polish translation updates

- includes/pages/game/ShowBuddyListPage.class.php
This should fix the errors that occurs if trying to communicate with players that have another language.
This bug was reported [here](https://steemit.com/utopian-io/@mwfiae/steemnova-error-message-on-friend-request)
> Fixed language issues between players

- includes/classes/missions/MissionCaseExpedition.class.php
According to http://owiki.de/Expedition
- changed resources found formula
- changed ship types found
- changed max factor based on top 1 player points
> Expedition found resources/ships formula

- styles/templates/game/page.alliance.admin.members.tpl
This closes the issue that louis88's [utopian.io post](https://steemit.com/utopian-io/@louis88/wrong-display-when-sorting-of-alliance-members) will create ;)
> Fix sorting in memberlist

- styles/templates/game/page.alliance.memberList.tpl
This will fix the issue that will be created by rivalzzz [utopian.io post](https://steemit.com/utopian-io/@rivalzzz/better-sorting-for-status-in-alliance-memberlist)
> Better sorting for status in memberlist

- includes/classes/class.MissionFunctions.php
Fixes the issue that will be created by [this bugreport](https://steemit.com/utopian-io/@mwfiae/steemnova-attack-report-is-in-the-wrong-language)
> Get the correct language for attack reports

- README.md
- includes/classes/missions/functions/GenerateReport.php
- includes/classes/missions/functions/calculateAttack.php
Completely rework of combat system:
- 1v1 instead of grouped ships fights
- true random shots
- armor does not regenerate each turn (bugfix)
- shields does break for each ship instead of "summarized shield"
- bounced shot if attack power less than 1% of enemy shield
- ships can explode if less than 70% of initial armor each round
- attack power does not range random +/-20% anymore. The randomness is high enough
- combat reports does not cut randomly (bugfix)
- optimization of arrays to Ds\Map and Ds\Vector (up to 10x less resources/time)
- tested on up to 500k units battle with success (1 core cpu, <128MB ram usage). For bigger battles the better server is needed or improve combat engine optimization.
Code require php-ds extension for array optimization. Instructions in README
Fixes …
> Combat system rework

- includes/pages/game/ShowFleetAjaxPage.class.php
Officers works also for galaxy view.
> Fix: Recyclers

- includes/pages/game/ShowAlliancePage.class.php
Fixes the issue that will be created by the utopian post from louis88
> Fix wrong stats for applications

- includes/pages/game/ShowAlliancePage.class.php
- styles/templates/game/page.alliance.home.tpl
Fixes https://github.com/steemnova/steemnova/issues/98
> Maximum allowed Member in Alliance-Page-Settings fix

- BBCodeParser2.ini
- README.md
- game.php
- includes/classes/BBCode.class.php
Thanks to @louis88-steemit for finding this bug!
> Fixed CSS Vulnerability caused by incorrect bb-code parsing

- admin.php
- includes/pages/game/ShowMessagesPage.class.php
- styles/templates/game/page.messages.default.tpl
- styles/templates/game/page.messages.view.tpl
- read messages subtraction fix
- removed ajax view refresh
- removed Operators list
- admin pages BBCodeParser2 fix
> Messages subtraction fix

- styles/templates/game/page.overview.default.tpl
in order to be able to see more than 3 posts if you are interested
> Href to steemnova feed on busy

- styles/templates/game/page.buildings.default.tpl
- styles/templates/game/page.empire.default.tpl
- styles/templates/game/page.officier.default.tpl
- styles/templates/game/page.records.default.tpl
- styles/templates/game/page.research.default.tpl
- styles/templates/game/page.resources.default.tpl
- styles/templates/game/page.shipyard.default.tpl
- styles/templates/game/shared.mission.spyReport.tpl
I changed the way the resource popups work, using "tooltip" instead of "tooltip_sticky"
> Resource tooltip patch

- styles/templates/game/page.fleetTable.default.tpl
This might not work, since I couldn't test it yet. It should work without problems though.
> Ship speed in tooltip

- styles/templates/game/page.buildings.default.tpl
- styles/templates/game/page.research.default.tpl
fixed the logic which choose the text for starting a research or building
> Fix for #82

- includes/pages/game/ShowOverviewPage.class.php
With this change, a deleted planet will change their internal planet id of research into your main planet id, since you can not delete it.
> Fix for #141

- language/de/ADMIN.php
- language/de/PUBLIC.php
I fixed a common German typo. ("Standart" instead of the correct "Standard")
> Fix German typos

- includes/pages/game/ShowResearchPage.class.php
This is fixed if you want to cancel from single queue, but cancelling X element from queue being built in another planet is not working properly.
> fix for deleting queue from different planets

- includes/pages/game/ShowTicketPage.class.php
> Users could watch tickets not owned by them

- includes/classes/class.FlyingFleetsTable.php
> Fix vision of enemy recycle missions in ally page

- includes/pages/adm/ShowNewsPage.php
Warning fix: "count(): Parameter must be an array or an object that implements Countable"
> ShowNewsPage.php warning count() fix

- language/en/TECH.php
Shield upgrade doesnt affect defenses(armor), so description was wrong.
+ some other updates to make description better
> Translation update
